Sylius\Component\Core\Model\ProductVariant:
    exclusion_policy: ALL
    xml_root_name: variant
    properties:
        price:
            expose: true
            type: integer
        sku:
            expose: true
            type: string
        onHold:
            expose: true
            type: integer
        onHand:
            expose: true
            type: integer
        sold:
            expose: true
            type: integer
